<?php
/**
 * @file
 * A short description of this module.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function digital_agency_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module's 'templates' directory.
  $module_path = backdrop_get_path('module', 'digital_agency') . '/templates';
  // Find all *.tpl.php files in this module's 'templates' folder recursively.
  $template_file_objects = backdrop_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme...
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

function digital_agency_preprocess_page(&$variables) {
  $variables['classes'][] = 'digital-agency';
  backdrop_add_icons(array('quotes'));
}
